### ISSUE TITLE
Automate Mapping Process

### ISSUE THREAD

**Issue by Decencies** [Nulldi/LCF-cheat#1]
Would be nice to see automation within this project.

Here are some resources that cover Lunar's obfuscation in-depth: https://github.com/Decencies/Articles/wiki/Lunar---Obfuscation

Here's a basic (Mixin) remapper for lunar client that can be incorporated to generate proguard -> srg mappings: https://github.com/Decencies/LunarRemapper

**Comment by Nulldi** [comment]
Hello, I will try to automate it in the near future but I am quite busy with school right now and thanks for the resources they will help me a lot.
